# Generated by Django 2.2.4 on 2019-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('subtheme', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('footnote', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
